[
    {
        "cve": "CVE-2022-34265",
        "poc_github": true,
        "full_name": "lnwza0x0a/CTF_Django_CVE-2022-34265",
        "owner_login": "lnwza0x0a",
        "owner_id": 96345719,
        "owner_html_url": "https://github.com/lnwza0x0a",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/96345719?v=4",
        "html_url": "https://github.com/lnwza0x0a/CTF_Django_CVE-2022-34265",
        "description": null,
        "fork": false,
        "created_at": "2022-09-08T21:22:28Z",
        "updated_at": "2022-10-07T11:01:14Z",
        "pushed_at": "2022-09-08T22:10:47Z",
        "stargazers_count": 1,
        "watchers_count": 1,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "[]",
        "visibility": "public",
        "forks": 0,
        "watchers": 1,
        "score": 0,
        "subscribers_count": 1
    }
]