[
    {
        "cve": "CVE-2024-24549",
        "poc_github": true,
        "full_name": "Abdurahmon3236/CVE-2024-24549",
        "owner_login": "Abdurahmon3236",
        "owner_id": 76862934,
        "owner_html_url": "https://github.com/Abdurahmon3236",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/76862934?v=4",
        "html_url": "https://github.com/Abdurahmon3236/CVE-2024-24549",
        "description": null,
        "fork": false,
        "created_at": "2024-08-02T21:05:34Z",
        "updated_at": "2024-12-09T05:12:31Z",
        "pushed_at": "2024-09-01T14:10:12Z",
        "stargazers_count": 4,
        "watchers_count": 4,
        "has_discussions": false,
        "forks_count": 0,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "[]",
        "visibility": "public",
        "forks": 0,
        "watchers": 4,
        "score": 0,
        "subscribers_count": 1
    },
    {
        "cve": "CVE-2024-24549",
        "poc_github": true,
        "full_name": "JFOZ1010/CVE-2024-24549",
        "owner_login": "JFOZ1010",
        "owner_id": 82562585,
        "owner_html_url": "https://github.com/JFOZ1010",
        "owner_avatar_url": "https://avatars.githubusercontent.com/u/82562585?v=4",
        "html_url": "https://github.com/JFOZ1010/CVE-2024-24549",
        "description": "Proof of concept of the CVE-2024-24549, Exploit in Python. ",
        "fork": false,
        "created_at": "2024-12-09T04:59:07Z",
        "updated_at": "2024-12-11T18:05:25Z",
        "pushed_at": "2024-12-09T05:09:43Z",
        "stargazers_count": 4,
        "watchers_count": 4,
        "has_discussions": false,
        "forks_count": 2,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": "[]",
        "visibility": "public",
        "forks": 2,
        "watchers": 4,
        "score": 0,
        "subscribers_count": 1
    }
]